---
title: "Loops & Functions"
author: "Elise Gonzales"
date: "2022-08-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

##Part 1

Task 1
```{r}
weekdays <- c("Mon", "Tues", "Wed", "Thurs", "Fri", "Sat", "Sun")
transects <- c("Transect A", "Transect B", "Transect C")

trans_out <- matrix(nrow = length(weekdays), ncol = length(transects))

for (i in seq_along(weekdays)) {
  for (j in seq_along(transects)) {
    val_out <- paste(weekdays[i], "-", transects[j])
          trans_out[i, j] <- val_out
  }
}
```

## Part 2

Task 2
```{r}
force <- function(mass, acceleration) {
  F <- (mass * acceleration)
  print(paste("The resulting force is", F, "Newtons"))
}

force(3, 2)
```

Task 3
```{r}
#Store columns
sci_name <- c("Chanos_chanos", "Sphyraena_barracuda", "Caranx")
common_name <- c("Milkfish", "Great_barracuda", "Giant_trevally")
a_est <- c(0.0905, 0.0181, 0.0353)
b_est <- c(2.52, 3.27, 3.05)

#Create data frame
fish_parms <- data.frame(sci_name, common_name, a_est, b_est)

#Create function

fish_weight <- function(fish_name, tot_length){
  fish.df <- filter(fish_parms, common_name == fish_name)
  a_est <- fish.df$a_est
  b_est <- fish.df$b_est
  weight <- a_est * (tot_length ^ b_est)
  return(weight)
}
fish_weight("Milkfish", 10)

```

